accent = "#e68e0d"
cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

color0 = "#333333"
color1 = "#D35F5F"
color2 = "#FFC107"
color3 = "#b91c1c"
color4 = "#e68e0d"
color5 = "#D35F5F"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"
